### ISSUE TITLE
live demo on PythonAnywhere

### ISSUE THREAD

**Issue by pdurbin** [garthg/petitions-visualization#1]
@garthg hi! The README says "A live demo is available at http://antislaverypetitions.pythonanywhere.com " but it seems to be down. Here's a screenshot:

![screen shot 2018-06-06 at 3 23 15 pm](https://user-images.githubusercontent.com/21006/41060445-bcd99e0c-699d-11e8-9522-70c55565a325.png)

I found http://www.yourhumblepetitioners.com/mapview/antislaverycongress and it looks like what I remember, I think. Here's a screenshot:

![screen shot 2018-06-06 at 3 26 39 pm](https://user-images.githubusercontent.com/21006/41060608-1bb75e3c-699e-11e8-988f-8dc28f8a9a8b.png)

So maybe the link in the README just needs to be updated?

**Comment by garthg** [comment]
You're quite right! Thanks @pdurbin for noticing and pointing it out. I'll update the README.

**Comment by garthg** [comment]
Fixed.
